######################################################################
# Automatically generated by qmake (2.01a) mié oct 31 11:46:27 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += GaussianCompleto.cpp

QMAKE_CXXFLAGS = -fopenmp
LIBS += -fopenmp
